r='support'
q='order'
p='guide'
o='bat'
n='mind'
m='morning'
l='competition'
k='trick'
j='impulse'
i='porter'
h='form'
g='country'
f='limit'
e='noise'
d='stretch'
c='verse'
b=KeyError
X=False
W='person'
V='smoke'
U=len
J=int
I=print
F=True
E=input
from random import choice as s
Y=['gate','history','stove','station',c,'selection',d,'cow','kittens','rule','metal','heat','birthday','blade','hand','walk','territory','spring','afternoon','frog',e,'creator','bottle','toy','worm','self','oven','rest','purpose',f,'dirt','pancake',V,'seed','army','boy','friction','yard','pull',g,'meal','society','aunt','girls','car','observation','pail','ring','scarf','trains','suggestion',h,'pencil','coal','texture','drain','receipt','liquid','deer','chalk',i,'statement',j,W,'business','loss',k,'touch','sack','cabbage','wilderness','partner',l,'instrument','minute','holiday','mitten',m,'poison','stone','hammer','end','pie','knowledge',n,'dad','fire',m,'winter','fireman','step','sticks','chin','grape','can','rake','spoon','treatment','weather','death',i,'queen','tent','look','bone','shelf','amount',o,'beds','sock','advertisement','blow','chickens','wall','toothpaste','flavor',e,'lake','ray','fear','memory','skirt','bucket','bridge','basketball','bear','crook','toothbrush','cause','cover','train','reaction','fuel','quill','dogs','unit','library','chance','scent',p,'committee','sign','degree','slave','creature','advice','iron','week','sofa','trade',g,'health','shape','sneeze','wealth','land','tray',V,'cave','boat','stocking',W,'notebook','bell','rain','bit','actor','animal','drop','throne','smash','songs','appliance','sound','coach','day','cushion','juice','month',c,'thaw','arrive','attempt','employ','glow',q,'realize','mate','untidy','arrange','face','complain','last','milk','multiply','live',o,'rescue','found','brake','film','compete','name','sip','mix','count','escape','bump','kneel','mourn','plant','join','grab','rot','comb','stain','shiver','store','bolt','beg','glue','miss','remind','chase','list','nail','stir','offer','jail','imagine','interest','develop','command','long','reply','head','applaud','divide','wipe','invent','attack','place','compare','carve','tug','allow','wander','shrug','melt','gaze','lick','fit','unlock','flow','reject','charge','supply','concern','undress','inform','wonder','provide','flower','suggest','camp','wobble','smell','influence','wail','kick','radiate',r,'reduce','increase','hunt','trip','moan','point','memorize','encourage','understanding','communication','recommendation','administration','entertainment','responsibility','transportation','establishment','differentiate','unaccountable','knowledgeable','disillusioned','environmental','heartbreaking','dysfunctional','psychological','sophisticated','lackadaisical','materialistic','administrative','overconfident','comprehensive','scintillating','education','sense',W,'apparatus','level',n,'cook','twist',j,'night','trouble','doubt','expert','profit','opinion','hour','canvas','destruction',d,V,'soup','existence','discussion',p,f,k,'wine','jelly','quality','polish','stop','drink','manager','cloth','sky','change','punishment','tax','food','laugh','fall','expansion','belief',r,'fiction','slip','cork','view','reason','force',h,'bread','disgust',q,'page','building','smile','part','pain',l]
t='WORD PREDICT!\nLevel:{0}\nPts req to lvl{1}:{2}\n1.Start a new game\n2.Settings\n3.Quit game\nOPTION NUMBER:'
u='SETTINGS|0 to quit\n1.Show first letter: \n{0}\n2.Show last letter: \n{1}\n3.Next page\nOPTION NUMBER:'
v='SETTINGS|0 to quit\n1.Guess tries:{0}\n2.gradual difficulty:\n{1}\n3.Credits\n4.Previous page\nOPTION NUMBER:'
w='Credits\nDeveloper:\nblabla_lab\nWords generated by: \nrandomlists.com\nCurrent words in game\n{0}'
def B(text):I('\n');I(text);E('PRESS EXE')
def S(x):
	if x:return X
	else:return F
K=F
L=X
M=6
G=M
N=0
T=3
O=0
P=F
y=3
while F:
	try:
		A=J(E(t.format(O,J(O+1),T-N)))
		if A==3:break
		elif A==2:
			while F:
				A=J(E(u.format(K,L)))
				if A==0:raise b()
				elif A==1:K=S(K)
				elif A==2:L=S(L)
				elif A==3:
					A=J(E(v.format(M,P)))
					if A==1:
						M=J(E('\n\nGuessing Tries\n(default:6,min:1,\nmax:20):\n\n'))
						if A>20:B('You set\nGuessing Tries\nto more than 20\n\n\n')
						elif A<=0:B('You set\nGuessing Tries\nto less than 1\n\n\n')
						else:G=A
					elif A==2:P=S(P)
					elif A==3:E(w.format(U(Y)))
					elif A==0:continue
	except ValueError:B('Only Numbers!');continue
	except b:continue
	I('LOADING...\nYou can always\nend a game by\npressing 1\n\n\n');Z=X
	if N==T:O+=1;T+=1
	if not P:Q=s(Y)
	else:0
	G=M;C=[]
	for R in Q:C.append(R)
	H=[];a=[]
	for R in C:H.append('_')
	if K:H[0]=C[0]
	if L:H[-1]=C[-1]
	while F:
		if Z:break
		I('Points:{0}\nTries:{2}\nLevel:{1}\n'.format(N,O,G));I(''.join(H));D=str(E('Guess a letter:\n')).lower()
		if D=='1':B('YOU QUITED!\nThe word was\n{}\n\n'.format(Q));break
		elif U(D)>1:B('Only one letter')
		elif D.isdigit():B('type a word,\nnot a digit!')
		if D in C:
			x=[A for A in range(U(C))if C[A]==D]
			for R in x:H[R]=D
			if H==C:B('YOU DID IT!\nThe word was\n{}\n\n'.format(Q));Z=F;N+=1;break
		else:
			I('WRONG')
			if G<=0:B('YOU LOSE!\nThe word was\n{}\n\n'.format(Q));break
			elif not G<=0 and not D in a:G-=1;a.append(D)