e='morning'
d='porter'
c=KeyError
V=False
U=len
O=int
M=print
H=True
G=input
from random import choice as W
P=['gate','history','stove','station','verse','selection','stretch','cow','kittens','rule','metal','heat',
'birthday','blade','hand','walk','territory','spring','afternoon','frog','noise','creator','bottle','toy',
'worm','self','oven','rest','purpose','limit','dirt','pancake','smoke','seed','army','boy','friction','yard',
'pull','country','meal','society','aunt','girls','car','observation','pail','ring','scarf','trains','suggestion',
'form','pencil','coal','texture','drain','receipt','liquid','deer','chalk',d,'statement','impulse','person',
'business','loss','trick','touch','sack','cabbage','wilderness','partner','competition','instrument','minute',
'holiday','mitten',e,'poison','stone','hammer','end','pie','knowledge','mind','dad','fire',e,'winter','fireman',
'step','sticks','chin','grape','can','rake','spoon','treatment','weather','death',d,'queen','tent','look','bone',
'shelf','amount','bat','beds','sock']
X='WORD PREDICT!\n1.Start a new game\n2.Settings\n3.Quit game\nTYPE THE NUMBER OF\nOPTION THEN \nPRESS EXE:'
Y='SETTINGS|0 to quit\n1.Show first letter: \n{0}\n2.Show last letter: \n{1}\n3.Next page\nOPTION NUMBER:'
Z='SETTINGS|0 to quit\n1.Guess tries: \n{0}\n2.Credits\n3.Previous page\nOPTION NUMBER:\n'
a='Credits\nDeveloper:\nblabla_lab\nWords generated by: \nrandomlists.com\nCurrent words in game\n{0}'
def B(text):M('\n');M(text);G('PRESS EXE')
def Q(x):
	if x:return V
	else:return H
I=H
J=V
N=6
E=N
R=0
while H:
	try:
		A=O(G(X))
		if A==3:break
		elif A==2:
			while H:
				A=O(G(Y.format(I,J)))
				if A==0:raise c()
				elif A==1:I=Q(I)
				elif A==2:J=Q(J)
				elif A==3:
					A=O(G(Z.format(E)))
					if A==1:
						N=O(G('\n\nGuessing Tries\n(default:6,min:1,\nmax:20):\n\n'))
						if A>20:B('You set\nGuessing Tries\nto more than 20\n\n\n')
						elif A<=0:B('You set\nGuessing Tries\nto less than 1\n\n\n')
						else:E=A
					elif A==2:G(a.format(U(P)))
					elif A==0:continue
	except ValueError:B('Only Numbers!');continue
	except c:continue
	S=V;K=W(P);E=N;C=[]
	for L in K:C.append(L)
	F=[];T=[]
	for L in C:F.append('_')
	if I:F[0]=C[0]
	if J:F[-1]=C[-1]
	B('You can always\nend a game by\npressing 1\n')
	while H:
		if S:break
		M('Points:{0}\nTries:{1}\n'.format(R,E));M(''.join(F));D=str(G('\nGuess a letter:\n')).lower()
		if D=='1':B('YOU QUITED!\nThe word was\n{}\n\n'.format(K));break
		elif U(D)>1:B('Only one letter')
		elif D.isdigit():B('type a word,\nnot a digit!')
		if D in C:
			b=[A for A in range(U(C))if C[A]==D]
			for L in b:F[L]=D
			if F==C:B('YOU DID IT!\nThe word was\n{}\n\n'.format(K));S=H;R+=1;break
		else:
			M('WRONG')
			if E<=0:B('YOU LOSE!\nThe word was\n{}\n\n'.format(K));break
			elif not E<=0 and not D in T:E-=1;T.append(D)